### ISSUE TITLE
Wallpaper settings shows a black page

### ISSUE THREAD

**Issue by locusf** [nemomobile-ux/glacier-settings#13]
When run with qmlscene error: 
`module org.nemomobile.glacier.settings not installed`

**Comment by locusf** [comment]
Issue still persists after upgrade and installation of nemo-qml-plugin-settings

**Comment by neochapay** [comment]
Can you build youself glacier-settings, run and put journalctl -xf /usr/bin/glacier-settings output here

**Comment by locusf** [comment]
Actually it was my own fault, I had a manually installed glacier-settings :/
