### ISSUE TITLE
Doesn't use libglacierapp

### ISSUE THREAD

**Issue by PureTryOut** [nemomobile-ux/glacier-settings#19]
The RPM package lists it as a runtime dependency, but if it were actually it would've been a compile time dependency as well like the other apps. `glacier-settings` doesn't actually use libglacierapp and thus does not abide to the `-w` parameter for example.

**Comment by neochapay** [comment]
https://github.com/nemomobile-ux/glacier-settings/blob/master/src/main.cpp#L31 use
https://github.com/nemomobile-ux/glacier-settings/blob/master/src/main.cpp#L40 use

**Comment by PureTryOut** [comment]
Ok interesting, then I wonder why it compiles perfectly fine without it :thinking:

**Comment by neochapay** [comment]
yeap windowed mode in libglacierapp https://github.com/nemomobile-ux/libglacierapp/blob/master/src/glacierapp.cpp#L98
